version: '3.4'

services:

  eurekaclient:
    container_name: eurekaclient
    build:
      context: .
      dockerfile: EurekaClient/Dockerfile
    ports:
      - "8080:80"
  authservice:
    container_name: authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "8081:80"
  movieservice:
    container_name: movieservice
    build:
      context: .
      dockerfile: MovieService/Dockerfile
    ports:
      - "8082:80"
  reviewservice:
    container_name: reviewservice
    build:
      context: .
      dockerfile: ReviewService/Dockerfile
    ports:
      - "8083:80"